### PR TITLE
Losen GMP dependency.

### PR DESCRIPTION
**Pull request by defr**
This extension is non standard, and right now only used for
something that can be trivially re-implemented in pure PHP.

Use the extension if it's available, otherwise calculate
the GCD directly.

### CODE REVIEW

**Comment by woprrr** [comment]
Thanks a lot defr !! JESUS WORK A CHARM !

**Comment by FGM** [comment]
Actually, I would have preferred to keep at least a mention about the use of GMP in the README and the hook_requirements, allbeit non-error, so that users can take nudged towards using gmp : some systems can use all the performance gains they can get, however minimal.

**Comment by defr** [comment]
@FGM Using gmp_gcd implies a conversion from int to GMP numbers, and then back to int through gmp_intval. On numbers that actually matters for real image resolutions, that probably shouldn't be much of a problem.

For example, have a look at:
* https://3v4l.org/ItD8A/perf#tabs
* https://3v4l.org/0HRtL/perf#tabs

**Comment by defr** [comment]
That being said though, there's indeed a problem with the code, because calculateGCD is kinda obviously missing a return $gcd; Fixing that

**Pull request merged**
